services:
  - type: web
    name: environmental-disaster
    env: python
    branch: main            # Git branch to deploy
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free               # optional, you can choose paid plan